version: "202106.0"

repository: spryker/spryker.github.io

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Spryker Documentation
# this appears on the top navigation bar next to the home button

site_title: Spryker Documentation
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Spryker
# this appears in the footer

github_editme_path: spryker/spryker.github.io/blob/master/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

google_analytics: ""
# if you have google-analytics ID, put it in. if not, edit this value to blank.

feedback_disable: true

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - static.json
  - node_modules/
  - vendor
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
# these are the files and directories that jekyll will exclude from the build

highlighter: rouge
# library used for syntax highlighting

markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

plugins:
  - jekyll-feed

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      topnav: topnav
  - scope:
      path: "docs/marketplace"
      type: "pages"
    values:
      product: marketplace
  -
    scope:
      path: "docs/marketplace/dev"
      type: "pages"
    values:
      sidebar: marketplace_dev_sidebar
      product-type: 'marketplace/dev'
      role: "dev"
  -
    scope:
      path: "docs/marketplace/user"
      type: "pages"
    values:
      sidebar: marketplace_user_sidebar
      product-type: 'marketplace/user'
      role: "user"

# version-related scopes
  -
    scope:
      path: "docs/**/202106.0"
    values:
      version: "202106.0"

# versioned categories - these must match corresponding directories
versioned_categories:
  marketplace:
    user:
      - features
      - back-office-user-guides
      - merchant-portal-user-guides
    dev:
      - feature-integration-guides
      - glue-api-guides

# these are defaults used for the frontmatter for these file types

sidebars:
  - marketplace_dev_sidebar
  - marketplace_user_sidebar

description: "Spryker documentation center."
# the description is used in the feed.xml file

# needed for sitemap.xml file only
# url: http://idratherbewriting.com
# baseurl: /documentation-theme-jekyll


github: [metadata]

search: algolia

algolia:
  application_id: 'IBBSSFT6M1'
  search_only_api_key: '296ac9c40fa95441b2d89d1fd8395bb4'
  indices:
    - name: 'marketplace_user'
      title: 'Marketplace User'
    - name: 'marketplace_dev'
      title: 'Marketplace Developer'
